server:
   # 随机端口
   port: 0
spring:
  application:
    name: hwctask
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/C0-S3-Py-hwc?useSSL=false
    username: root
    password: a
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: MYSQL
    properties:
      hibernate:
        format_sql: true

logging:
   level:
#      root: debug
      com:
         yc: debug