# step 1
server:
  port: 8003
  
# step 2
spring:
  application:
    name: cloud-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka
      
# step 3
# java 运行 --spring.profiles.active=u02
# mvn  运行 -Dspring.profiles.active=u02
---
spring:
  profiles: u01
server:
  port: 8004
---
spring:
  profiles: u02
server:
  port: 8005