#server.port=80
#server.port.a=true
#server.port.b=true

server:
   port: 80

# 日志配置
logging:
  level:
    com:
      yc:
        game:
          dao: debug
          web: warn
  
  

